import type { Metadata } from "next";
import "./globals.css";
import "./font.css";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer/Footer";

export const metadata: Metadata = {
  title: "Nest Nepal",
  description: "Generated by Nest Nepal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
